# Use the same python version with ray
FROM python:3.10.14

WORKDIR /root/opea-finetune

RUN --mount=type=cache,target=/var/cache/apt apt-get update -y \
    && apt-get install -y vim htop net-tools dnsutils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# COPY ./install-llm-on-ray.sh /tmp/install-llm-on-ray.sh
# RUN --mount=type=cache,target=/root/.cache/pip /tmp/install-llm-on-ray.sh

COPY ./ .

RUN --mount=type=cache,target=/root/.cache/pip cd ./llm-on-ray && pip install -v -e .[cpu] --extra-index-url https://download.pytorch.org/whl/cpu --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/cpu/us/

RUN --mount=type=cache,target=/root/.cache/pip pip install --no-cache-dir --upgrade -r requirements.txt

RUN echo 'source $(python -c "import oneccl_bindings_for_pytorch as torch_ccl; print(torch_ccl.cwd)")/env/setvars.sh' >> ~/.bashrc

CMD ["bash", "-c", "./run.sh"]