# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

#!/bin/sh
envsubst '${FRONTEND_SERVICE_IP} ${FRONTEND_SERVICE_PORT} ${BACKEND_SERVICE_NAME} ${BACKEND_SERVICE_IP} ${BACKEND_SERVICE_PORT} ${DATAPREP_SERVICE_IP} ${DATAPREP_SERVICE_PORT} ${BACKEND_CODEGEN_SERVICE_NAME} ${BACKEND_CODEGEN_SERVICE_IP} ${BACKEND_CODEGEN_SERVICE_PORT} ${BACKEND_DOCSUM_SERVICE_NAME} ${BACKEND_DOCSUM_SERVICE_IP} ${BACKEND_DOCSUM_SERVICE_PORT} ${BACKEND_CHAT_HISTORY_SERVICE_NAME} ${BACKEND_CHAT_HISTORY_SERVICE_IP} ${BACKEND_CHAT_HISTORY_SERVICE_PORT} ${BACKEND_PROMPT_SERVICE_NAME} ${BACKEND_PROMPT_SERVICE_IP} ${BACKEND_PROMPT_SERVICE_PORT} ${KEYCLOAK_SERVICE_NAME} ${KEYCLOAK_SERVICE_IP} ${KEYCLOAK_SERVICE_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/default.conf
nginx -g 'daemon off;'
