# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# HABANA environment
FROM vault.habana.ai/gaudi-docker/1.17.1/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest as hpu

ENV LANG=en_US.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
    git-lfs \
    libgl1-mesa-glx \
    libjemalloc-dev

RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    chown -R user /home/user/

#USER user

RUN git lfs install

COPY comps /home/user/comps



RUN pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.17.1
RUN pip install git+https://github.com/huggingface/optimum-habana@v1.13.2

RUN cd /home/user/comps/lvms/llama-vision/  \
    pip install --no-cache-dir --upgrade pip && \
    pip install transformers-4.45.0.dev0-py3-none-any.whl && \
    bash update


ENV PYTHONPATH=/root:/home/user

WORKDIR /home/user/comps/lvms/llama-vision/

ENTRYPOINT ["python", "lvm_tp.py"]
