# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# HABANA environment
FROM vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0 AS hpu
RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    chown -R user /home/user/

COPY comps /home/user/comps

RUN chown -R user /home/user/comps/text2image

RUN rm -rf /etc/ssh/ssh_host*

# Set environment variables
ENV HABANA_VISIBLE_DEVICES=all
ENV OMPI_MCA_btl_vader_single_copy_mechanism=none
ENV DEBIAN_FRONTEND="noninteractive"  TZ=Etc/UTC
ENV LANG=en_US.UTF-8
ENV PYTHONPATH=/home/user:/usr/lib/habanalabs/:/home/user/optimum-habana

# Install linux packages
RUN apt-get update && apt-get install -y ocrmypdf \
    && rm -rf /var/lib/apt/lists/*

# Install requirements and optimum habana
RUN    pip install --no-cache-dir pip==24.0 \
    && pip install --no-cache-dir langchain-huggingface==0.1.0 \
    && pip install --no-cache-dir langchain-community==0.3.1 \
    && pip install --no-cache-dir langchain==0.3.1 \
    && pip install --no-cache-dir protobuf==3.20.2 \
    && pip install --no-cache-dir grpcio-tools==1.62.1 \
    && pip install --no-cache-dir pdfminer.six==20221105 \
    && pip install --no-cache-dir pypdf==4.3.1 \
    && pip install --no-cache-dir transformers==4.43.1 \
    && pip install --no-cache-dir optimum-habana==1.13.2 \
    && pip install --no-cache-dir sentence-transformers==3.0.1 \
    && pip install --no-cache-dir huggingface_hub==0.23.2

RUN    pip install --no-cache-dir docx2txt==0.8 \
    && pip install --no-cache-dir unstructured==0.12.6 \
    && pip install --no-cache-dir urllib3==1.26.18 \
    && pip install --no-cache-dir bitsandbytes==0.43.0 \
    && pip install --no-cache-dir requests==2.31.0 \
    && pip install --no-cache-dir pydantic==2.6.4 \
    && pip install --no-cache-dir python-multipart==0.0.9 \
    && pip install --no-cache-dir fastapi==0.110.0 \
    && pip install --no-cache-dir uvicorn==0.29.0 \
    && pip install --no-cache-dir pdfplumber==0.11.0 \
    && pip install --no-cache-dir python-jose[cryptography] \
    && pip install --no-cache-dir scikit-learn==1.5.2

# graph RAG dependencies
RUN   pip install --no-cache-dir neo4j==5.23.0 \
    && pip install --no-cache-dir llama-index==0.11.20 \
    && pip install --no-cache-dir llama-index-graph-stores-neo4j==0.3.5 \
    && pip install --no-cache-dir langchain_experimental==0.3.2 \
    && pip install --no-cache-dir json_repair==0.30.0

RUN   pip install  --no-cache-dir llama-index-llms-huggingface==0.3.5 \
    && pip install --no-cache-dir pyprojroot==0.3.0 \
    && pip install  --no-cache-dir llama-index-embeddings-huggingface==0.3.1 \
    && pip install  --no-cache-dir llama-index-llms-huggingface-api==0.2.0 \
    && pip install  --no-cache-dir llama-index-graph-stores-neo4j==0.3.5 \
    && pip install  --no-cache-dir llama-index-embeddings-langchain==0.2.1  \
    && pip install  --no-cache-dir InstructorEmbedding==1.0.1

USER user
WORKDIR /home/user/comps/text2image/src

RUN echo python opea_text2image_microservice.py --device hpu --use_hpu_graphs --bf16 >> run.sh

CMD bash run.sh

