# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# HABANA environment
FROM vault.habana.ai/gaudi-docker/1.20.1/ubuntu22.04/habanalabs/pytorch-installer-2.6.0 AS hpu

ENV LANG=en_US.UTF-8
ARG REPO=https://github.com/huggingface/optimum-habana.git
ARG REPO_VER=v1.17.0

RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
    git-lfs \
    libgl1-mesa-glx \
    libjemalloc-dev

RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    mkdir -p /home/user/logs && \
    chown -R user /home/user/

RUN git lfs install

COPY comps /home/user/comps

ARG uvpip='uv pip install --system --no-cache-dir'
RUN pip install --no-cache-dir --upgrade pip setuptools uv && \
    pip install --no-cache-dir optimum-habana && \
    pip install --no-cache-dir git+https://github.com/HabanaAI/DeepSpeed.git@1.20.0

RUN git clone ${REPO} --depth 1 --branch ${REPO_VER} /home/user/optimum-habana && rm -rf /home/user/optimum-habana/.git

WORKDIR /home/user/optimum-habana/examples/text-generation
RUN $uvpip -r requirements.txt

WORKDIR /home/user/comps/llms/src/text-generation/
RUN $uvpip -r requirements.txt && \
    $uvpip --upgrade --force-reinstall pydantic numpy==1.26.4 transformers==4.49.0

ENV PYTHONPATH=/root:/home/user
ENV HABANA_LOGS=/home/user/logs

USER user

WORKDIR /home/user/comps/llms/src/text-generation/

ENTRYPOINT ["bash", "entrypoint.sh"]
