# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# HABANA environment
FROM vault.habana.ai/gaudi-docker/1.20.1/ubuntu22.04/habanalabs/pytorch-installer-2.6.0 AS hpu

ENV LANG=en_US.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
    git-lfs \
    libgl1-mesa-glx \
    libjemalloc-dev

RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    mkdir -p /home/user/logs && \
    chown -R user /home/user/

RUN git lfs install

COPY comps /home/user/comps

RUN pip install --no-cache-dir --upgrade pip setuptools && \
    pip install --no-cache-dir --upgrade-strategy eager optimum[habana] && \
    pip install --no-cache-dir git+https://github.com/HabanaAI/DeepSpeed.git@1.19.0

RUN pip install --no-cache-dir git+https://github.com/huggingface/optimum-habana.git@transformers_future && \
    cd /home/user/comps/llms/src/text-generation/ && pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir soundfile peft backoff

ENV PYTHONPATH=/root:/home/user
ENV HABANA_LOGS=/home/user/logs

WORKDIR /home/user/comps/llms/src/text-generation/

ENTRYPOINT ["bash", "entrypoint_phi4.sh"]
