# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Use a base image
FROM openeuler/python:3.11.13-oe2403lts

# Set this to "cpu" or "gpu" or etc
ARG ARCH="cpu"

RUN yum update -y && yum install -y \
    mesa-libGL \
    jemalloc-devel \
    shadow && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    chown -R user /home/user/

COPY comps /home/user/comps

ARG uvpip='uv pip install --system --no-cache-dir'
RUN pip install --no-cache-dir --upgrade pip setuptools uv && \
    if [ ${ARCH} = "cpu" ]; then \
      $uvpip torch torchvision --index-url https://download.pytorch.org/whl/cpu; \
      $uvpip -r /home/user/comps/llms/src/faq-generation/requirements-cpu.txt; \
    else \
      $uvpip -r /home/user/comps/llms/src/faq-generation/requirements-gpu.txt; \
    fi

ENV PYTHONPATH=$PYTHONPATH:/home/user

USER user

WORKDIR /home/user/comps/llms/src/faq-generation

ENTRYPOINT ["python", "opea_faqgen_microservice.py"]
