# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

INPUT:
  SIZE: (96, 96)
  TRANSFORMS: ["random_flip", "random_translation", "normalize"]

DATASET:
  NAME: "miniDomainNet"

MODEL:
  BACKBONE:
    NAME: "resnet18"
